[kubernetes]
enable = true
[kubernetes.hostPort]
max_port = 9000
min_port = 8000

[alibabacloud]
enable = true
[alibabacloud.slb]
max_port = 700
min_port = 500
[alibabacloud.nlb]
max_port = 1500
min_port = 1000

[volcengine]
enable = true
[volcengine.clb]
max_port = 700
min_port = 500
