[kubernetes]
enable = true
[kubernetes.hostPort]
max_port = 9000
min_port = 8000

[alibabacloud]
enable = true
[alibabacloud.slb]
max_port = 700
min_port = 500
block_ports = [593]
[alibabacloud.nlb]
max_port = 1502
min_port = 1000
block_ports = [1025, 1434, 1068]

[hwcloud]
enable = true
[hwcloud.elb]
max_port = 700
min_port = 500
block_ports = []

[volcengine]
enable = true
[volcengine.clb]
max_port = 600
min_port = 550
block_ports = [593]

[aws]
enable = false
[aws.nlb]
max_port = 30050
min_port = 30001

[jdcloud]
enable = false
[jdcloud.nlb]
max_port = 700
min_port = 500

[tencentcloud]
enable = true
[tencentcloud.clb]
min_port = 700
max_port = 750
